import { buildMetadata } from "@/lib/metadata";
import LegalPageLayout from "@/components/legal/LegalPageLayout";

export const metadata = buildMetadata({
  title: "Disclaimer",
  description: "Read the Toolkno disclaimer covering general information, tool accuracy, user responsibility, and liability limits.",
  path: "/disclaimer"
});

export default function DisclaimerPage() {
  return (
    <LegalPageLayout
      eyebrow="Legal"
      title="Disclaimer"
      intro="The information and tools provided on Toolkno are for general informational and utility purposes only. By using this website, you agree to this disclaimer in full."
      sections={[
        {
          heading: "No Professional Advice",
          subheading: "General Information Only",
          body: ["Toolkno tools do not provide professional, legal, financial, medical, or technical advice. The results generated by our tools should not be relied upon as a substitute for professional consultation."]
        },
        {
          heading: "Tool Accuracy",
          subheading: "No Guarantees",
          body: ["While we strive to keep all tools accurate and up to date, Toolkno makes no warranties or guarantees regarding the accuracy, completeness, or reliability of any tool output."]
        },
        {
          heading: "User Responsibility",
          subheading: "Use at Your Own Risk",
          body: ["Any action you take based on the results obtained from Toolkno tools is strictly at your own risk. Toolkno will not be liable for any losses or damages arising from the use of our tools."]
        },
        {
          heading: "External Links",
          subheading: "Third-Party Content",
          body: ["Toolkno may contain links to external websites for additional information. We do not control or take responsibility for the content or accuracy of third-party websites."]
        },
        {
          heading: "Limitation of Liability",
          subheading: "Platform Liability",
          body: ["Under no circumstances shall Toolkno be liable for any direct, indirect, incidental, or consequential damages resulting from the use or inability to use the website or its tools."]
        },
        {
          heading: "Changes to This Disclaimer",
          subheading: "Updates",
          body: ["We reserve the right to modify this Disclaimer at any time without notice. Any changes will be effective immediately upon posting."]
        },
        {
          heading: "Contact Information",
          subheading: "Questions",
          body: ["If you have any questions regarding this Disclaimer, please contact us at support@toolkno.com."]
        }
      ]}
    />
  );
}
